apigee/microgateway-plugins

- oauth/index.js
add request defaults if available as in volos-analytics-apigee
> add support for request defaults

- package.json
Missing modules from two plugins.
> Missing packages.

- analytics/index.js
An alternative approach to masking.
> Mask specific fields

- test/verify-api-key-test.js
- verify-api-key/index.js
> Fixes for issue 26

- analytics/index.js
> Updating to use xff header to set the client_ip in analytics.

- analytics/index.js
Make sure that analytics plugin cannot cause inability to complete request handling
> add failsafe around analytics plugin

- analytics/index.js
- oauth/index.js
Better analytics (capture target analytics)
Add support for grace period/clock tolerance for oauth
> Analytics and OAuth

- healthcheck/index.js
- healthcheck/package.json
Adding support for cf healthcheck based on the proxy target port.
> Adding CF Port check

- oauth/index.js
Store API key in cache if cacheKey is true
> Store API key in cache

- README.md
Change the heading tags of Plugins at the top, subheadings and some text improvements.
> fix(documentation): fix heading tags

- cors/index.js
Fix https://github.com/apigee/microgateway-plugins/issues/72
> Cors plugin : add Access-Control-Allow-Origin for all HTTP methods

- contentlength/index.js
- index.js
b127687184
Adds a contentlength plugin to calculate transformed body.
> contentlength

- quota/index.js
Quota fix for month timer, fix is dependent on volos github merge.
https://github.com/relloller/volos/tree/30days
> 30days interval

- analytics/index.js
- apikeys/index.js
- bauth/index.js
- extauth/index.js
- lib/basicAuth.js
- oauth/index.js
- oauthv2/index.js
The logger.error are replaced with logger.eventLog and missing params are passed.
If details are available logger calls should have object with below details:
level, req, resp, err, component name. Second argument to function is custom message.
> Updating runtime logger calls to use logger.eventLog

- apikeys/index.js
- eurekaclient/index.js
- extauth/index.js
- lib/basicAuth.js
- oauth/index.js
- oauthv2/index.js
Convert console statements to logger.consoleLog statements.
> Convert console statements to logger.consoleLog statements.

- apikeys/index.js
- eurekaclient/index.js
- extauth/index.js
- lib/basicAuth.js
- oauth/index.js
- oauthv2/index.js
- test/accumulate-request-test.js
- test/microgateway-core.js
- test/oauth-test.js
- test/quota-test.js
Create new objects logger and stats which acts as interface of actual objects from microgateway-core.
Passing empty objects to plugins init function could cause run time errors, So removing those.
> Travis build failure fix and logging phase 3

- extauth/index.js
- oauthv2/index.js
Fix the issue introduced in 3.0.5 due to incorrect error code being set.
> for306 Set correct error code

- quota/index.js
Set quota identifer to 'appname.productname' instead of just 'appname'
> 139526406 correct the quota identifier

- oauth/index.js
add failOpen and failopenGraceInterval configuration to oauth.
If failOpen is true and failopenGraceInterval is set the old token is used in case of 5xx errors in verifyApiKey call.
To use this feature set in oauth config as:
oauth:
failopenGraceInterval: 5 (in seconds, old token will be used for this time duration)
failOpen: true
This feature is applicable only if oauth.cacheKey is set to true.
> 140025210 add failOpen config to oauth

- bauth/README.md
Please review this plugin documentation and merge with the master branch.
> adding README for bauth plugin

- oauthv2/README.md
Adding a README for the oauthv2 plugin.
> Oauthv2 readme

- apikeys/README.md
I added README for the apikeys plugin.
> Apikeys readme

- quota/README.md
I added a README for the quota plugin.
> Quota readme

- oauth/README.md
Please review this documentation and accept the pull request.
> Added a README file for the OAuth plugin. 

- npm-shrinkwrap.json
- oauth/index.js
- package.json
Set correct ttl value in milliseconds to apiKeyCache and validTokenCache.
Add failopenGraceInterval to apiKeyCache ttl and remove usage of sharedMemory.
> 142375660 set correct ttl to cache

- npm-shrinkwrap.json
- package.json
- quota/index.js
Use 'volos-quota-redis' if useRedis is set true and otherwise use 'volos-quota-apigee'.
> Add volos-quota-redis to quota plugin

- oauth/index.js
- test/oauth-test.js
Changed resource pattern spelling mistake 'asterik' thanks to Philipp Schleier; changed regexs to match all four patterns /, /, /**, //2/. Added test coverage. Need to update documentation on EMG to note that edgemicro_auth needs to be a standalone product added to the app configuration via management console not in a proxy product config.
> PR for bug b142677575

- quota/index.js
Pass custom logger object to volos. This logger object will call logger.eventLog internally.
Change quota logs format to event log.
> Fix bug 144187500

- quota/index.js
use edgemicro.redisPassword if set in config and pass the same in options.auth_pass to create function of redisQuota object
> set auth_pass if redisPassword is set

- apikeys/index.js
- lib/validateResourcePath.js
- oauth/index.js
- oauthv2/index.js
- test/apikeys-test.js
- test/microgateway-core.js
- test/oauth-test.js
- test/validate-resource-path-test.js
Update pattern matching logic in checkIfAuthorized function of oauth plugin to support patterns: 1. /{literal}** 2. /{literal}*.
Add the functional coverage for checkIfAuthorized function.
Add common test cases for oauth, oauthv2.
Add exception handling to pattren maching logic.
Code cleanup for oauth-test.js.
Rectify typo errors.
> fix bug 147027862.

- analytics/index.js
Add target_url, target_basepath and target_host in analytics record.
> Fix bug 146456699

- spikearrest/README.md
Added a readme for the spikearrest plugin. Please review.
> added spikearrest readme.

- cloud-foundry-route-service/README.md
Added a README for the cloud-foundry-route-service-plugin.  Please review this pull request.
> Added a README for the cloud-foundry-route-service-plugin

- lib/validateResourcePath.js
- test/validate-resource-path-test.js
Replace all '*'s by regex in the pattern instead of a single replace.
Add unit test case for multiple '*'s in product pattern.
> 152822846 Correct product pattern match logic

- quota/index.js
Add ORG.ENV to the quota identifier for redis implementation.
> 152005003 Update quota identifier

- lib/validateResourcePath.js
- test/validate-resource-path-test.js
Update regex for '*' to match "everything up until the next /".
Add more test cases for '/*'.
> 152822846 Update regex for '*'

- test/quota-test.js
Update quota test cases to pass org and env values.
> 152005003 update quota test cases

- index.js
- metrics/index.js
- metrics/package.json
A plugin collect stat for requests coming in to the EMG and the responses going back from the EMG
> Add metrics plugin

- json2xml/index.js
Set 'Content-Type' header in on_request handler instead of 'onend_request'.
> 156986819 Set headers in on_request

- apikeys/index.js
- lib/AuthorizationHelper.js
- oauth/index.js
- oauthv2/index.js
Read jwk keys values correctly and allow tokens from old key for 30 mins.
> 155499600 Fix key rotation issue

- json2xml/index.js
In json2xml plugin remove the global variables for control flags and set on 'req' object.
> 158529319 Set flags on request object

- apikeys/index.js
- lib/basicAuth.js
- oauth/index.js
- oauthv2/index.js
Remove 'oauthtoken' from the logs
> 161583962 Remove token from logs

- quota/index.js
- test/quota-test.js
Use emgConfigs to read 'product_to_proxy','proxies' and 'edgemicro.global'.
> 160431789 Use emgConfigs in quota plugin

- index.js
- metrics/README.md
- metrics/index.js
- metrics/package.json
Alpha version of Metrics plugin
> Emg metrics plugin - Alpha

- apikeys/index.js
- lib/basicAuth.js
- oauth/index.js
- oauthv2/index.js
Set the decoded token on request object before checking for authorisation because analytics needs the developer info.
> 133162200 Make developer info available to analytics plugin

- quota/index.js
Create single redis connection and pass the client to quota object.
> 158618994 Consolidate redis clients

- accesscontrol/README.md
- accesscontrol/index.js
142808699 Fixed issues in accesscontrol plugin and provided proper documentation in readme
> For accesscontrol plugin

- oauth/index.js
Add event logger into oauth plugin if verify apikey get failed.
> 149256174 Add logger into oauth plugin

- accesscontrol/README.md
Fixed alignment issues in config examples
>  update accesscontrol plugin readme

- .travis.yml
Add node js 14 in travis test.
> 172295489 Add node js 14 in travis test

- apikeys/README.md
- apikeys/index.js
Remove the gracePeriod info from readme file.
Code cleanup for gracePeriod.
> b/178341593 Update readme file of apikey plugin

- analytics/index.js
Add 'target_response_code' property in ax record
> 179971737 Add target status code in ax record

- lib/validateResourcePath.js
- test/validate-resource-path-test.js
Added regex pattern to handle trailing slash in url path
Added test cases to verify request behaviour in case of trailing slash
> 183910111 Fix url path issue with trailing slash

- lib/helperFunctions.js
Added null check validation before stringifying the data
> 233315475 Fix data parsing issue

- analytics/index.js
- lib/basicAuth.js
- lib/validateResourcePath.js
Refactor code to determine the API product based on request
> 283947053 Fix wrong product populating in analytics

- apikeys/index.js
- apikeys/package.json
- extauth/index.js
- extauth/package-lock.json
- extauth/package.json
- futures/oauth/index.js
- futures/oauth/package.json
- futures/oauthv2/package.json
- npm-shrinkwrap.json
- oauth/index.js
- oauth/package.json
- oauthv2/index.js
- oauthv2/package.json
- package.json
- test-net-live/quotaBugTest.js
- Replaced deprecated 'request' with 'postman-request', an actively maintained fork.
- Updated and bumped versions of several vulnerable dependencies to enhance security.
> 293735012 Security Fixes and Dependency Updates
